### ISSUE TITLE
Duplicate value for resource 'attr/showDivider'

### ISSUE THREAD

**Issue by igorka48** [Omega-R/OmegaRecyclerView#89]
After updating Android Studio to 3.2 and buildTools to 28.0.3 can receive error:

> Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
> error: duplicate value for resource 'attr/showDivider' with config ''.

This is in reason you use very common name for attribute showDivider and many other libraries might use the same. 
You can change it with pattern libprefix_atrrname or in other way

How to reproduce:
 - add to build.gradle
```
    implementation 'com.google.android:flexbox:0.3.2'
    implementation 'com.github.Omega-R:OmegaRecyclerView:1.7.6@aar'
```

**Comment by R12rus** [comment]
@igorka48 
We have change attr name to dividerShow. This changes will be in next release.
